[package]
authors = ["The Nushell Project Developers"]
description = "A binary used by tests"
edition = "2021"
license = "MIT"
name = "nu-testbin"
version = "0.1.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
